defaults:
  - train
  - override data: eval_bvem
  - _self_

num_shots: 3
lr: 0.00001
devices: [0]
run_name: rmsbvessel
path_to_chkpt: runs/rmsbvessel/260717a/pretrain_260717a_last.ckpt #TODO
chkpt_folder:  runs/vesselfm/finetune #TODO

dataloader:
  num_workers: 0 # permet au finetune de fonctionner sans erreur de GPU CUDA
  prefetch_factor: null
  persistent_workers: False
  shuffle: False

trainer:
  lightning_trainer:
    val_check_interval: 200
    max_steps: 1200
    max_epochs: 1

  lightning_module:
    _target_: vesselfm.seg.module.PLModuleFinetune
    _partial_: True
    prediction_threshold: 0.62
    batch_size: ${batch_size}
    input_size: ${input_size}

    scheduler_configs:
      cosine_annealing_few:
        interval: step
        frequency: 10
        scheduler:
          _target_: torch.optim.lr_scheduler.CosineAnnealingLR
          _partial_: True
          T_max: 1000
          eta_min: 0.0000001
          last_epoch: -1

      linear_warmup: null 
      cosine_annealing: null