defaults:
  - data: real_drand_flow
  - trainer: default
  - model: dyn_unet_base
  - hydra: default
  - _self_

# data
input_size: [128, 128, 128]
image_channels: 1
num_classes: 1

# training
seed: 404
lr: 0.0001
batch_size: 8 # lié au val_check_interval dans configs/trainer/default.yaml
eval_path: data/evaluation #TODO
path_to_chkpt: null
devices: [0]

# logging
run_name: 260717a
wandb_project: rmsbvessel
chkpt_folder: runs #TODO
offline: True # permet de skip la connexion à wandb

# dataloader
dataloader:
  _target_: "torch.utils.data.DataLoader"
  _partial_: True
  num_workers: 16
  prefetch_factor: 3
  batch_size: ${batch_size}
  pin_memory: True
  persistent_workers: True
  shuffle: True